### ISSUE TITLE
Using SENSOR_DELAY_UI

### ISSUE THREAD

**Issue by niqo01** [nvanbenschoten/motion#11]
Reading at the documentation [SENSOR_DELAY_UI](http://developer.android.com/reference/android/hardware/SensorManager.html#SENSOR_DELAY_UI) seams more appropriate instead of `SensorManager.SENSOR_DELAY_FASTEST`

**Comment by nvanbenschoten** [comment]
During initial development of the library, I looked into using a slower sensor delay. A slower rate would certainly be preferred because of battery concerns. Unfortunately I found that `SensorManager.SENSOR_DELAY_FASTEST` is the only sampling period that allows the parallax effect to exist without significant jank and maintain a steady 60 fps frame rate.

**Comment by niqo01** [comment]
@nvanbenschoten would it be possible to add the possibility to the library users to tweak this value according to their need?

**Comment by nvanbenschoten** [comment]
If you want to throw together a pull request that gives `ParallaxImageView.registerSensorManager()` an optional sensor delay parameter with a default delay of `SensorManager.SENSOR_DELAY_FASTEST`, I wouldn't see a problem with that.
